### ISSUE TITLE
did you try upscale before UHDB ?

### ISSUE THREAD

**Issue by iperov** [YuanfeiHuang/CoMoNet#1]
did you try bicubic upscale x4 before UHDB , thus the network will just enhance x1 picture ?

**Comment by YuanfeiHuang** [comment]
Hi, thanks for your question.
As pre-upscaling the LR image will largely increase the time complexity, we only tried the post-upscaling the LR features after UHDB. For x1 pictures (for image denoising or image deblurring), you can remove the upscaling module and fine-tune the pre-trained models.

**Comment by iperov** [comment]
ok
